### ISSUE TITLE
[Feature] Option for `delay` to take precedence over `event` to trigger prerendering

### ISSUE THREAD

**Issue by ghost** [mubaidr/prerender-plugin#12]
Thanks for the plugin! Working much smoother than `prerender-spa-plugin` so far.

Some of my pages don't trigger the `capture` event intentionally and would be great if the `delay` could take precedence over this. From experience and peeking at your code it looks like if the `capture` event is set then the `delay` will never trigger a prerender. Is this true?

If so, is this something you think this plugin would be interested in using?

**Comment by mubaidr** [comment]
Sounds a good use-case. Will be adding this soon.

**Comment by mubaidr** [comment]
Implemented this in: https://github.com/mubaidr/prerender-plugin/commit/bd8283802cc1dedf292bee311a958491b1370d6d & https://github.com/mubaidr/prerender-plugin/commit/bd00b4140ff66d66fb698fb018053428b032863a
