### ISSUE TITLE
add examples for all options

### ISSUE THREAD

**Issue by codeofsumit** [mubaidr/prerender-plugin#13]
It'd be great to have examples for all available options to see how they work. (Currently trying out the webpack plugin)

**Comment by mubaidr** [comment]
This directory contains examples for node.js and webpack usage:
https://github.com/mubaidr/prerender-plugin/tree/master/examples

I will add commented options as an example to the same examples.

**Comment by mubaidr** [comment]
https://github.com/mubaidr/prerender-plugin/commit/629696d7ca668310a3ac221bab9215a392ee8e11
