### ISSUE TITLE
Add optional optimizations

### ISSUE THREAD

**Issue by mubaidr** [mubaidr/prerender-plugin#7]
Study and add following options (if beneficial):

- [x] html minification
- [x] add prefetchlinks

**Comment by stereobooster** [comment]
You also can use https://github.com/peterbe/minimalcss

**Comment by mubaidr** [comment]
Interesting. Will check it. 👍

**Comment by mubaidr** [comment]
https://github.com/mubaidr/prerender-plugin/commit/4f9274fd267b8a8b9e9eb76fdb6d2e471ff40afc
