### ISSUE TITLE
edge cases

### ISSUE THREAD

**Issue by stereobooster** [mubaidr/prerender-plugin#9]
- you can use `await page.goto(pageUrl, { waitUntil: "networkidle0" });` to catch page content after all activity finished
- you also need to make sure state of the form elements saved https://github.com/stereobooster/react-snap/issues/84
- CSS-in-JS solutions work https://github.com/stereobooster/react-snap/issues/76
- remove `blob:` URLs from HTML, because they don't make sense in generated HTML

**Comment by mubaidr** [comment]
https://github.com/mubaidr/prerender-plugin/commit/cfdc7b13d13dc44ec13295fae66a405b0ba24205
